update packages and deploys

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -1,7 +1,6 @@
 name: PHPCS check
 on:
     pull_request:
-    # Allow manually triggering the workflow.
     workflow_dispatch:
 
 # Cancel all previous workflow runs for the same branch that have not yet completed.
@@ -10,36 +9,52 @@ concurrency:
     cancel-in-progress: true
 
 jobs:
-    phpcs:
-        name: PHPCS check
+    check-changes:
         runs-on: ubuntu-latest
+        outputs:
+            changed_files: ${{ steps.check-php-files.outputs.changed_files }}
         steps:
             - name: Checkout code
               uses: actions/checkout@v4
 
-            - name: Setup PHP
-              uses: 'shivammathur/setup-php@v2'
-              with:
-                  php-version: 'latest'
-                  ini-values: memory_limit=256M'
-                  coverage: none
-                  tools: cs2pr
+            - name: Check for PHP file changes
+              id: check-php-files
+              run: |
+                  git fetch origin ${{ github.base_ref }}
+                  git fetch origin ${{ github.head_ref }}
+                  CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- | grep '\.php$' || true)
+                  if [ -z "$CHANGED_FILES" ]; then
+                      echo "No changed files"
+                      echo "changed_files=false" >> "$GITHUB_OUTPUT"
+                  else
+                      echo "PHP files changed"
+                      echo "changed_files=true" >> "$GITHUB_OUTPUT"
+                  fi
 
-            - name: Install Composer dependencies
-              uses: 'ramsey/composer-install@v3'
-              with:
-                  # Bust the cache at least once a month - output format: YYYY-MM.
-                  custom-cache-suffix: $(date -u "+%Y-%m")
+    phpcs:
+        needs: check-changes
+        if: needs.check-changes.outputs.changed_files  == 'true'
+        uses: choctaw-nation/shared-github-actions/.github/workflows/phpcs.yml@main
 
-            - name: Run PHPCS Beautifier
-              id: phpcbf
-              continue-on-error: true
-              run: composer phpcbf
+    get-previous-status:
+        needs: check-changes
+        if: needs.check-changes.outputs.changed_files == 'false'
+        runs-on: ubuntu-latest
+        steps:
+            - name: Get previous PHPCS status
+              run: |
+                  echo "No PHP files changed. Retrieving previous PHPCS status..."
 
-            - name: Run PHPCS checks
-              id: phpcs
-              run: composer phpcs
-
-            - name: Show PHPCS results in PR
-              if: ${{ always() && steps.phpcs.outcome == 'failure' }}
-              run: cs2pr ./phpcs-report.xml
+    final-check:
+        needs: [phpcs, get-previous-status]
+        runs-on: ubuntu-latest
+        if: always()
+        steps:
+            - name: Ensure at least one job passed
+              run: |
+                  if [[ "${{ needs.phpcs.result }}" == "success" || "${{ needs.get-previous-status.result }}" == "success" ]]; then
+                      echo "Checks passed."
+                  else 
+                        echo "Checks failed."
+                        exit 1
+                  fi
